name: Build PySide6 GUI App

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller csv-splitter.py --clean --noupx --noconsole --noconfirm --onefile --windowed --icon=app_icon.ico

      - name: Rename artifact
        run: |
          mkdir dist_upload
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/main.exe dist_upload/CSV_Splitter_windows.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/main dist_upload/CSV_Splitter_macos
          else
            mv dist/main dist_upload/CSV_Splitter_linux
          fi
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: dist_upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
